// import '@/app/globals.css'
// import type { Metadata } from "next"
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang="en" className={inter.className}>
//       <body className="antialiased">
//         {children}
//       </body>
//     </html>
//   )
// }




// app/layout.tsx (Root layout)
import '@/app/globals.css'
import type { Metadata } from "next"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Elim Christian Garden International',
    default: 'Elim Christian Garden International', // Fallback when no title is provided
  },
  description: "Elim Christian Garden International - A place for spiritual growth and community",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  )
}